apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cs-cassandra
spec:
  ports:
  - name: cql
    port: 9042
    protocol: TCP
  - name: internode
    port: 7000
    protocol: TCP
  - name: tls-internode
    port: 7001
    protocol: TCP
  selector:
    app: cs-cassandra
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cs-cassandra
spec:
  template:
    metadata:
      labels:
        app: cs-cassandra
    spec:
      containers:
      - name: cassandra
        image: gcr.io/google-samples/cassandra:v11
        command:
          - /run.sh
        env:
          - name: MAX_HEAP_SIZE
            value: 2048M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEED_PROVIDER
            value: "io.k8s.cassandra.KubernetesSeedProvider"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 9042
        - containerPort: 7000
        - containerPort: 7001
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: cas-data
      volumes:
      - name: cas-data
        hostPath:
          path: /data/cassandra
      nodeSelector:
        "coscale/workload.data": "true"
