apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: cs-haproxy
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32080
    protocol: TCP
  - name: https
    port: 443
    nodePort: 32443
    protocol: TCP
  selector:
    app: cs-haproxy
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cs-haproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-haproxy
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: haproxy
        image: docker.coscale.com/coscale/haproxy:1.0.8407
        ports:
        - containerPort: 80
        - containerPort: 443
      nodeSelector:
        "coscale/workload.interactive": "true"
