apiVersion: v1
kind: ReplicationController
metadata:
  name: cs-mailer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-mailer
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: mailer
        image: docker.coscale.com/coscale/mailer:1.0.8407
        env:
        - name: API_SUPER_USER
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.super.email
        - name: API_SUPER_PASSWD
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.super.passwd
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.api.url
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.app.url
        - name: FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.from
        - name: MAIL_SERVER
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.server
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.port
        - name: MAIL_SSL
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.use_ssl
        - name: MAIL_AUTH
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.use_auth
        - name: MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.username
        - name: MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: coscale-config
              key: coscale.email.password
      nodeSelector:
        "coscale/workload.worker": "true"
