apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: cs-memcached
spec:
  ports:
  - port: 11211
    protocol: TCP
  selector:
    app: cs-memcached
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cs-memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-memcached
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: memcached
        image: docker.coscale.com/coscale/memcached:1.0.8407
        ports:
        - containerPort: 11211
      nodeSelector:
        "coscale/workload.interactive": "true"
