apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: cs-rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
  selector:
    app: cs-rabbitmq
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cs-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-rabbitmq
    spec:
      imagePullSecrets:
      - name: coscale-registry
      containers:
      - name: rabbitmq
        image: docker.coscale.com/coscale/rabbitmq:1.0.8407
        ports:
        - containerPort: 5672
      nodeSelector:
        "coscale/workload.interactive": "true"
